#!/bin/bash
set -ue

cd ~/mcgillij.dev/content || exit
touch index.rst
sphinx-build -b gemini -C . ../gem_capsule *.rst
cd pages/
touch index.rst
sphinx-build -b gemini -C . ../../gem_capsule *.rst
cd ..
rm -rf ../gem_capsule/\{static\}/
rm index.rst
python ~/gits/rst2gem/rst2gem.py > ../gem_capsule/index.gmi

cd ../gem_capsule || exit
for filename in ./*.gmi; do
	sed -i 's/{static}//g' "${filename}"
done
cp -Rupv ../content/images ./
gemfeed -n 25 -b gemini://gemini.mcgillij.dev -t 'DevOops' -s "@mcgillij's blog"
cd ..
scp -r gem_capsule ryzen:
